name: Security scan

on: 
  push: {}
  pull_request: 
    branches: ["main"]
  workflow_dispatch: {}

jobs: 
  SAST_scan:
    name: SAST code scanning
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout Code
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: sonarCube scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{secrets.SONAR_ACTIONS_SCAN}}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=AshishDora_devSecOps
            -Dsonar.organization=ashishdora
